syntax on 
set nu 
set cursorline
set clipboard=unnamedplus
set relativenumber
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab
set smartindent
set hidden
set incsearch
set ignorecase
set smartcase
set scrolloff=1
set colorcolumn=80
set encoding=utf-8
set nobackup
set nowritebackup
set splitright
set splitbelow
set autoread
set mouse=a
set nowrap
filetype on
filetype plugin on
filetype indent on
set guicursor=n-v-c-i:block
