-- Basic settings
vim.cmd('syntax on')
vim.cmd('set nu')
vim.cmd('set cursorline')
vim.cmd('set clipboard=unnamedplus')
vim.cmd('set relativenumber')
vim.cmd('set tabstop=4')
vim.cmd('set softtabstop=4')
vim.cmd('set shiftwidth=4')
vim.cmd('set expandtab')
vim.cmd('set smarttab')
vim.cmd('set smartindent')
vim.cmd('set hidden')
vim.cmd('set incsearch')
vim.cmd('set ignorecase')
vim.cmd('set smartcase')
vim.cmd('set scrolloff=1')
vim.cmd('set colorcolumn=80')
vim.cmd('set encoding=utf-8')
vim.cmd('set nobackup')
vim.cmd('set nowritebackup')
vim.cmd('set splitright')
vim.cmd('set splitbelow')
vim.cmd('set autoread')
vim.cmd('set mouse=a')
vim.cmd('set nowrap')
vim.cmd('filetype on')
vim.cmd('filetype plugin on')
vim.cmd('filetype indent on')
vim.cmd('set guicursor=n-v-c-i:block')
